# Native image build
FROM quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-17 AS build

USER root
RUN microdnf install findutils

COPY --chown=quarkus:quarkus . /code
USER quarkus
WORKDIR /code
RUN ./mvnw package -Dnative -DskipTests -Dquarkus.native.native-image-xmx=4g

# Native runtime
FROM quay.io/quarkus/quarkus-micro-image:2.0

WORKDIR /app

COPY --from=build /code/target/*-runner /app/application
COPY --from=build /code/models /app/models

RUN chmod 775 /app/application

EXPOSE 8080

ENV MODEL_PATH=/app/models

ENTRYPOINT ["/app/application", "-Dquarkus.http.host=0.0.0.0"]
