quarkus.application.name=sklearn-model-service
quarkus.application.version=1.0.0-SNAPSHOT

quarkus.http.port=8080
quarkus.http.test-port=8081

model.path=models/iris_classifier.onnx
model.input.features=4

quarkus.log.level=INFO
quarkus.log.console.enable=true

quarkus.native.resources.includes=models/**

quarkus.health.extensions.enabled=true
quarkus.health.openapi.included=true
