FROM maven:3.9.6-eclipse-temurin-17 AS build
COPY pom.xml /tmp/
COPY src /tmp/src/
COPY scripts /tmp/scripts/
WORKDIR /tmp/

RUN apt-get update && apt-get install -y python3 python3-pip && \
    pip3 install --break-system-packages -r scripts/requirements.txt && \
    python3 scripts/train_model.py && \
    mvn -B package

FROM registry.access.redhat.com/ubi8/openjdk-17:1.18
ENV LANGUAGE='en_US:en'
COPY --from=build /tmp/target/quarkus-app/lib/ /deployments/lib/
COPY --from=build /tmp/target/quarkus-app/*.jar /deployments/
COPY --from=build /tmp/target/quarkus-app/app/ /deployments/app/
COPY --from=build /tmp/target/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 8080
USER 185
ENV JAVA_OPTS_APPEND="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV JAVA_APP_JAR="/deployments/quarkus-run.jar"

ENTRYPOINT [ "/opt/jboss/container/java/run/run-java.sh" ]
